package com.example.ui.components

object FilterConstants {
    val GENRES = listOf(
        "All",
        "Aboriginal", "Abstract", "Acid", "Acid House", "Acid Jazz", "Acid Rock", "Acoustic", 
        "African", "Afrobeat", "Afro-Cuban", "Afro-Cuban Jazz", "Aguinaldo", "Alternative Metal", 
        "Alternative Rock", "Alt-Pop", "Amapiano", "Ambient", "Ambient House", "Anarcho-Punk", 
        "Anatolian Rock", "Andalusian Classical", "Andean Music", "Anison", "Antifolk", "AOR", 
        "Appalachian Music", "Arabic Pop", "Arena Rock", "Art Rock", "Art Song", "Atmospheric Black Metal", 
        "Atonal", "Audiobook", "Avantgarde", "Avant-garde Jazz", "Axé", "Azonto", "Bachata", 
        "Baião", "Bakersfield Sound", "Balearic", "Ballad", "Ballet", "Ballroom", "Baltimore Club", 
        "Bambuco", "Banda", "Bangladeshi Classical", "Barbershop", "Baroque", "Baroque Pop", 
        "Basque Music", "Bassline", "Bass Music", "Batucada", "Bayou Funk", "Beat", "Beatbox", 
        "Beatdown", "Beguine", "Bengali Music", "Berlin-School", "Bhangra", "Big Band", "Big Beat", 
        "Bitpop", "Blackgaze", "Black Metal", "Bleep", "Bluegrass", "Blues", "Blues Rock", "Bolero", 
        "Bollywood", "Bomba", "Bongo Flava", "Boogaloo", "Boogie", "Boogie Woogie", "Boom Bap", "Bop", 
        "Bossanova", "Bossa Nova", "Bounce", "Bouncy Techno", "Brass Band", "Brass Instrument", 
        "Brass & Military", "Breakbeat", "Breakcore", "Break-In", "Breaks", "Brega", "Britcore", 
        "Britpop", "Brit Pop", "Broken Beat", "Brutal Death Metal", "Bubblegum", "Bubbling", "Byzantine", 
        "Cabaret", "Caipira", "Cajun", "Calypso", "Cambodian Classical", "Candombe", "Cantata", "Cantopop", 
        "Cantorial", "Canzone Napoletana", "Cape Jazz", "Capriccio", "Carimbó", "Carnatic", "Catalan Music", 
        "Celtic", "Chacarera", "Cha-Cha", "Chamamé", "Chamber Music", "Champeta", "Chanson", "Charanga", 
        "Chicago Blues", "Chillwave", "Chinese Classical", "Chiptune", "Choral", "Choro", "Chutney", 
        "City Pop", "Classical", "Classical Guitar", "Classic Rock", "Cloud Rap", "Cobla", "Coldwave", 
        "Comedy", "Comfy Synth", "Compas", "Concert Band", "Concert Film", "Concerto", "Concerto Grosso", 
        "Conjunto", "Conscious", "Contemporary", "Contemporary Jazz", "Contemporary R&B", "Cool Jazz", 
        "Copla", "Corrido", "Country", "Country Blues", "Country Rock", "Cretan", "Crossover thrash", 
        "Crunk", "Crust", "Cuatro", "Cubano", "Cumbia", "Currulao", "Cut-up/DJ", "Dabke", "Dancehall", 
        "Dance-pop", "Dances", "Dangdut", "Dansband", "Danzon", "Dark Ambient", "Dark Electro", "Dark Jazz", 
        "Darkwave", "Deathcore", "Death Metal", "Deathrock", "Deconstructed Club", "Deep House", "Deep Techno", 
        "Delta Blues", "Depressive Black Metal", "Descarga", "Desert Blues", "Dialogue", "Disco", "Disco Polo", 
        "Dixieland", "DJ Battle Tool", "Donk", "Doomcore", "Doom Metal", "Doo Wop", "Downtempo", "Dream Pop", 
        "Drill", "Drone", "Drum n Bass", "Dub", "Dub Poetry", "Dubstep", "Dub Techno", "Dungeon Synth", 
        "Duranguense", "Early", "East Coast Blues", "Easy Listening", "EBM", "Education", "Educational", 
        "Electric Blues", "Electro", "Electroacoustic", "Electroclash", "Electro House", "Electronic", "Electro Swing", 
        "Emo", "Enka", "Éntekhno", "Erotic", "Ethereal", "Ethno-pop", "Etude", "Eurobeat", "Eurodance", 
        "Euro-Disco", "Euro House", "Europop", "Euro Trance", "Exotica", "Experimental", "Fado", "Fantasia", 
        "Favela Funk", "Field Recording", "Filk", "Flamenco", "Folk", "Folk Metal", "Folk Rock", "Folk, World, & Country", "Footwork", 
        "Forró", "Free Funk", "Free Improvisation", "Free Jazz", "Freestyle", "Freetekno", "French House", 
        "Frevo", "Funaná", "Funeral Doom Metal", "Funk", "Funk Metal", "Funkot", "Funk / Soul", "Fusion", "Future Bass", 
        "Future House", "Future Jazz", "Future Pop", "Futurism", "Gabber", "Gagaku", "Gaita", "Galician Traditional", 
        "Gamelan", "Gangsta", "Garage House", "Garage Rock", "Geet", "G-Funk", "Għana", "Ghazal", "Ghetto", 
        "Ghetto House", "Ghettotech", "Glam", "Glitch", "Glitch Hop", "Gnawa", "Goa Trance", "Gogo", "Go-Go", 
        "Goregrind", "Gospel", "Gothic Metal", "Goth Rock", "Gqom", "Grime", "Grindcore", "Griot", "Groove Metal", 
        "Group Sounds", "Grunge", "Guaguancó", "Guajira", "Guaracha", "Guarania", "Guggenmusik", "Gusle", 
        "Gwo Ka", "Gypsy Jazz", "Halftime", "Hands Up", "Happy Hardcore", "Hard Beat", "Hard Bop", "Hardcore", 
        "Hardcore Hip-Hop", "Hard House", "Hard Rock", "Hardstyle", "Hard Techno", "Hard Trance", "Harmonica Blues", 
        "Harpsichord", "Harsh Noise Wall", "Hawaiian", "Health-Fitness", "Heavy Metal", "Highlife", "Hillbilly", 
        "Hill Country Blues", "Hindustani", "Hi NRG", "Hip Hop", "Hip-House", "Hiplife", "Hokkien Pop", "Holiday", 
        "Honkyoku", "Honky Tonk", "Horrorcore", "Horror Rock", "House", "Huayno", "Hyperpop", "Hyper Techno", 
        "Hyphy", "Hypnagogic pop", "IDM", "Illbient", "Impressionist", "Incidental Music", "Indian Classical", 
        "Indie Pop", "Indie Rock", "Indo-Pop", "Industrial", "Industrial Metal", "Instrumental", "Interview", 
        "Italodance", "Italo-Disco", "Italo House", "Izvorna", "Jangle Pop", "Jazz", "Jazzdance", "Jazz-Funk", "Jazz-Rock", 
        "Jazzy Hip-Hop", "J-Core", "Jersey Club", "Jibaro", "Jiuta", "Joropo", "Jota", "J-pop", "J-Rock", "Jug Band", 
        "Juke", "Jump Blues", "Jumpstyle", "Jungle", "Junkanoo", "Karaoke", "Kaseko", "Kayōkyoku", "Keroncong", 
        "Keyboard", "Khaliji", "Kizomba", "Klasik", "Klezmer", "Kolo", "Korean Court Music", "K-pop", "Krautrock", 
        "K-Rock", "Kuduro", "Kwaito", "Laïkó", "Lambada", "Lao Music", "Late Romantic", "Latin", "Latin Jazz", 
        "Latin Pop", "Leftfield", "Lento Violento", "Levenslied", "Lied", "Light Music", "Liscio", "Lo-Fi", 
        "Louisiana Blues", "Lounge", "Lovers Rock", "Low Bap", "Lowercase", "Luk Krung", "Luk Thung", "Lullaby", 
        "Madrigal", "Magnificat", "Makina", "Maloya", "Mambo", "Mandopop", "Manila Sound", "Marcha Carnavalesca", 
        "Marches", "Mariachi", "Marimba", "Mass", "Mathcore", "Math Rock", "Mbalax", "Medical", "Medieval", 
        "Melodic Death Metal", "Melodic Hardcore", "Memphis Blues", "Memphis Rap", "Mento", "Merengue", "Metalcore", 
        "Miami Bass", "Microhouse", "Midwest Emo", "Military", "Milonga", "Minimal", "Minimalism", "Minimal Techno", 
        "Minneapolis Sound", "Min'yō", "Mizrahi", "Mod", "Modal", "Modern", "Modern Classical", "Modern Electric Blues", 
        "Mo Lam", "Monolog", "Moombahton", "Morna", "Motet", "Mouth Music", "Movie Effects", "MPB", "Mugham", 
        "Musette", "Música Criolla", "Musical", "Music Hall", "Music Video", "Musique Concrète", "Nagauta", "NDW", 
        "Neo-Classical", "Neo-Classical Metal", "Neofolk", "Néo Kyma", "Neopagan", "Neo-Romantic", "Neo Soul", 
        "Neo Trance", "Népzene", "Nerdcore Techno", "New Age", "New Beat", "New Jack Swing", "New Wave", "Nhạc Vàng", 
        "Nintendocore", "Nocturne", "Noise", "Noisecore", "Noise Rock", "Non-Music", "Nordic", "Norteño", "Novelty", "No Wave", 
        "Nu-Disco", "Nueva Cancion", "Nueva Trova", "Nu Metal", "Nursery Rhymes", "Occitan", "Occult", "Oi", 
        "Ojkača", "Opera", "Operetta", "Oratorio", "Orchestra", "Organ", "Ottoman Classical", "Overtone Singing", 
        "Overture", "Pachanga", "Pacific", "Pagode", "Parody", "Pasodoble", "Passion", "Percussion Ensemble", 
        "Persian Classical", "Persian Pop", "P.Funk", "Philippine Classical", "Phleng Phuea Chiwit", "Phonk", 
        "Piano", "Piano Blues", "Piedmont Blues", "Piobaireachd", "Pipe & Drum", "Plainchant", "Plena", 
        "Plunderphonics", "Poetry", "Political", "Polka", "Pop", "Pop Punk", "Pop Rap", "Pop Rock", "Pornogrind", 
        "Porro", "Post Bop", "Post-Grunge", "Post-Hardcore", "Post-Metal", "Post-Modern", "Post-Punk", "Post Rock", 
        "Power Electronics", "Power Metal", "Power Pop", "Power Violence", "Prelude", "Program Music", "Progressive Bluegrass", 
        "Progressive Breaks", "Progressive House", "Progressive Metal", "Progressive Trance", "Prog Rock", 
        "Promotional", "Psychedelic", "Psychedelic Rock", "Psychobilly", "Psy-Trance", "Public Broadcast", 
        "Public Service Announcement", "Pub Rock", "Punk", "Qawwali", "Quechua", "Radioplay", "Ragga", "Ragga HipHop", 
        "Ragtime", "Raï", "Ranchera", "Rapso", "Rebetiko", "Reggae", "Reggae Gospel", "Reggae-Pop", "Reggaeton", 
        "Religious", "Renaissance", "Requiem", "Rhapsody", "Rhythm & Blues", "Rhythmic Noise", "RnB/Swing", 
        "Rock", "Rockabilly", "Rock Opera", "Rock & Roll", "Rocksteady", "Rōkyoku", "Romani", "Romantic", "Roots Reggae", 
        "Rumba", "Rune Singing", "Russian Pop", "Ryūkōka", "Salegy", "Salsa", "Samba", "Samba-Canção", "Sámi Music", 
        "Schlager", "Schranz", "Score", "Screamo", "Screw", "Sean-nós", "Sea Shanties", "Séga", "Sephardic", 
        "Serenade", "Seresta", "Serial", "Sermon", "Sertanejo", "Shaabi", "Shibuya-Kei", "Shidaiqu", "Shinkyoku", 
        "Shoegaze", "Shomyo", "Ska", "Skiffle", "Skweee", "Slowcore", "Sludge Metal", "Smooth Jazz", "Snap", "Soca", 
        "Soft Rock", "Sokyoku", "Solo", "Son", "Sonata", "Sonero", "Son Montuno", "Soukous", "Soul", "Soul-Jazz", 
        "Sound Art", "Sound Collage", "Sound Poetry", "Soundtrack", "Southern Rock", "Space-Age", "Space Rock", 
        "Special Effects", "Spectralism", "Speech", "Speedcore", "Speed Garage", "Speed Metal", "Spiritual Jazz", 
        "Spirituals", "Spoken Word", "Sport", "Stage & Screen", "Steel Band", "Stoner Rock", "Story", "Stride", "String Ensemble", 
        "String Instrument", "Suite", "Sunshine Pop", "Suomisaundi", "Surf", "Swamp Pop", "Swing", "Swingbeat", 
        "Symphonic Metal", "Symphonic Rock", "Symphony", "Synth-pop", "Synthpunk", "Synthwave", "Taarab", "Tamburitza", 
        "Tamil Film Music", "Tango", "Tech House", "Technical", "Technical Death Metal", "Techno", "Tech Trance", 
        "Te Deum", "Tejano", "Texas Blues", "Thai Classical", "Theme", "Theme With Variations", "Therapy", "Thrash", 
        "Thug Rap", "Timba", "Toasting", "Tone Poem", "Trallalero", "Trance", "Trap", "Tribal", "Tribal House", 
        "Trip Hop", "Tropical House", "Trova", "Turntablism", "Twelve-tone", "Twist", "UK Funky", "UK Garage", 
        "UK Street Soul", "Unblack Metal", "Vallenato", "Vaporwave", "Vaudeville", "Video Game Music", "Viking Metal", 
        "Villancicos", "Vocal", "Vocaloid", "Volksmusik", "V-pop", "Waiata", "Western Swing", "Wind Ensemble", 
        "Witch House", "Woodwind Instrument", "Yemenite Jewish", "Yé-Yé", "Yoruba", "Zamba", "Zarzuela", "Zemer Ivri", 
        "Zhongguo Feng", "Zouk", "Zydeco"
    ).distinct()

    val REGIONS = listOf(
        "All",
        "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Anguilla", "Antigua & Barbuda", "Argentina", 
        "Armenia", "Aruba", "Asia", "Australasia", "Australia", "Australia & New Zealand", "Austria", "Austria-Hungary", 
        "Azerbaijan", "Bahamas, The", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgian Congo", "Belgium", 
        "Belize", "Benelux", "Benin", "Bermuda", "Bolivia", "Bosnia & Herzegovina", "Botswana", "Brazil", "Brunei", 
        "Bulgaria", "Burkina Faso", "Burma", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", 
        "Central America", "Chile", "China", "Colombia", "Congo, Democratic Republic of the", "Congo, Republic of the", 
        "Costa Rica", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czechoslovakia", "Czech Republic", "Czech Republic & Slovakia", 
        "Dahomey", "Denmark", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Estonia", "Ethiopia", 
        "Europe", "Faroe Islands", "Finland", "France", "France & Benelux", "French Guiana", "French Polynesia", "Gabon", 
        "Gambia, The", "Georgia", "German Democratic Republic (GDR)", "Germany", "Germany, Austria, & Switzerland", 
        "Germany & Switzerland", "Ghana", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", 
        "Guinea", "Guinea-Bissau", "Gulf Cooperation Council", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungary", 
        "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle Of Man", "Israel", "Italy", "Ivory Coast", 
        "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Korea (pre-1945)", "Kosovo", "Kuwait", "Kyrgyzstan", 
        "Laos", "Latvia", "Lebanon", "Lesotho", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", 
        "Malaysia", "Maldives", "Mali", "Malta", "Man, Isle of", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", 
        "Mexico", "Middle East", "Moldova, Republic of", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Namibia", 
        "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", 
        "North America (inc Mexico)", "North Korea", "North & South America", "Norway", "Pakistan", "Palestine", "Panama", 
        "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Protectorate of Bohemia and Moravia", 
        "Puerto Rico", "Qatar", "Reunion", "Rhodesia", "Romania", "Russia", "Russia & CIS", "Saint Kitts and Nevis", "Saint Lucia", 
        "Saint Vincent and the Grenadines", "San Marino", "Saudi Arabia", "Scandinavia", "Senegal", "Serbia", "Serbia and Montenegro", 
        "Seychelles", "Sierra Leone", "Singapore", "Singapore & Malaysia", "Singapore, Malaysia & Hong Kong", 
        "Singapore, Malaysia, Hong Kong & Thailand", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", 
        "South Africa", "South America", "South East Asia", "Southern Rhodesia", "South Korea", "South Vietnam", "Spain", 
        "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tanzania", "Thailand", "Togo", 
        "Trinidad & Tobago", "Tunisia", "Turkey", "Uganda", "UK", "UK & Europe", "UK, Europe & Israel", "UK, Europe & Japan", 
        "UK, Europe & US", "UK & France", "UK & Germany", "UK & Ireland", "Ukraine", "UK & US", "United Arab Emirates", 
        "Upper Volta", "Uruguay", "US", "USA & Canada", "USA, Canada & Europe", "USA, Canada & UK", "USA & Europe", "USSR", 
        "Uzbekistan", "Venezuela", "Vietnam", "Virgin Islands", "Worldwide", "Yemen", "Yugoslavia", "Zaire", "Zambia", "Zimbabwe"
    ).distinct()
    
    val STYLES = listOf(
        "All", "Acoustic", "Alternate Take", "Collector's Edition", "Cover", "Exclusive", "Extended Version", 
        "Live", "Remix", "Soundtrack", "Studio Session", "Unplugged"
    )
}
